### ISSUE TITLE
Hey, I would like to discuss about number parser library.

### ISSUE THREAD

**Issue by Manish-210** [noviluni/noviluni#3]
Hi, myself manish 
I am interested in understanding and expanding number parser library and also contributing to it for the upcoming gsoc. I wanted to discuss some things over private chat if possible for you.
Contact information of myself:
linkedin : https://www.linkedin.com/in/manish-prajapati-9970641a0/

**Comment by noviluni** [comment]
Hi @Manish-210!

Thank you for showing interest in participating in the upcoming GSoC!

We can discuss it, as it is definitely a good idea to improve the `number-parser` library as part of the GSoC, but we can use the [`number-parser` project issue tracker](https://github.com/scrapinghub/number-parser/issues) instead of a private chat, as it doesn't fit well with the idea of Open Source projects, where all is discussed publicly. :slightly_smiling_face: 

Feel free to open a new issue in that project with your ideas/proposals. :smile:

**Comment by Manish-210** [comment]
Hey @noviluni 
Sorry to bother you again. Do you know which idea to work on for `number-parser` library in GSoC ([ there ](https://gsoc2021.zyte.com/ideas)was not any listed idea )? Also, who will be the mentor for this library?

**Comment by noviluni** [comment]
Hi @Manish-210, sorry for the late answer, I'm really busy these days. 

The `number-parser` doesn't appear in the list of ideas but it's kind of a part of `dateparser`, so you can apply it with your ideas. As you can find here: https://gsoc2021.zyte.com/participate

> These are just our ideas, feel free to come up with your own ideas:
> 
> 1. To discuss your own idea for one of our projects, open a issue on the GitHub page of the corresponding project.
> 2. To discuss an idea for a new project related to web crawling or data processing technologies, contact us at opensource@zyte.com.


We wanted to integrate `number-parser` into `dateparser` and `price-parser`, so maybe you can work on that. Feel free to comment here: https://github.com/scrapinghub/dateparser/issues/612 if you have a good idea on how to improve the library/integrate it, etc.
